import Head from "next/head";

import SearchTopo from "@/components/SearchTopo/SearchTopo";
import Notification from "@/components/Notification/Notification";

export default function notificationsPage() {
  return (
    <>
      <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchTopo />
      <Notification />
      <Notification />
      <Notification />
      <Notification />
    </>
  );
}
